# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shs < Formula
  desc "A CLI tool that splits chained shell commands into individual commands"
  homepage "https://github.com/gurisugi/shs"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.8/shs_darwin_amd64.tar.gz"
      sha256 "d8e6b2f9696dd01df1deef44e80a99b1ed9e20b4010b6983ddaac7d79f2ba433"

      define_method(:install) do
        bin.install "shs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.8/shs_darwin_arm64.tar.gz"
      sha256 "ffe72ea06e7ebcb1b9bbfdd42e978061ebe95508cf52f7cb769261283abb8b4b"

      define_method(:install) do
        bin.install "shs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.8/shs_linux_amd64.tar.gz"
      sha256 "72608fdb95c67621971d60c898989869959fd33a397b789b93606032e8a06705"
      define_method(:install) do
        bin.install "shs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.8/shs_linux_arm64.tar.gz"
      sha256 "796ddc7cde43f2faf8894b35eff6dbdaf4d3ff4a26c2ebb4cf3711f67e2513db"
      define_method(:install) do
        bin.install "shs"
      end
    end
  end
end
