# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shs < Formula
  desc "A CLI tool that splits chained shell commands into individual commands"
  homepage "https://github.com/gurisugi/shs"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.9/shs_darwin_amd64.tar.gz"
      sha256 "27d9b660ff6457c4061cf7e269b71d4af1aba8dee39958f6d3ecbea2c0d749f4"

      define_method(:install) do
        bin.install "shs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.9/shs_darwin_arm64.tar.gz"
      sha256 "33779fe68cfe7a84e56dad62fb788f5c68b9252c5451a00a68970d572ad619b7"

      define_method(:install) do
        bin.install "shs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.9/shs_linux_amd64.tar.gz"
      sha256 "9c800da3d4fed50899260cfcd849a1bf5d7c1b7628647ef4deba516334fda3d8"
      define_method(:install) do
        bin.install "shs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gurisugi/shs/releases/download/v0.0.9/shs_linux_arm64.tar.gz"
      sha256 "69ab7e083d8fe12242b0688f7aa41dc5673c628a10bd3692f893c69446f7fc13"
      define_method(:install) do
        bin.install "shs"
      end
    end
  end
end
